run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: pr-reviewer-service

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number